### ISSUE TITLE
invalid interface error running with karma from gruntfile

### ISSUE THREAD

**Issue by readelobdill** [ghempton/mocha-lazy-bdd#1]
I'm getting ```Uncaught Error: invalid interface "lazy-bdd"``` when running ```grunt karma``` after a clean installation. I'm hoping you might understand this problem better than me but i'll give it shot!

I've got
```
karma: {
    unit: {
        configFile: 'karma.config.js',
        client: {
          mocha: {
            reporter: 'html', // change Karma's debug.html to the mocha web reporter
            ui: 'lazy-bdd'
          }
       }
    }
 }
```

in my Gruntfile config

I've gotten it to work by just adding 'lazy-bdd' into the mocha.js file and it works but is not a sustainable solution.

**Comment by ghempton** [comment]
We don't use grunt to run our tests, so I am not sure off the top of my head what is wrong here. Would be much appreciated if you could get to the bottom of this!

**Comment by stalniy** [comment]
@readelobdill this is actually an issue of `karma-mocha` package. The mocha is setup before custom ui is included on the page: https://github.com/karma-runner/karma-mocha/issues/84

**Comment by ghempton** [comment]
Thanks for looking into this.

**Comment by readelobdill** [comment]
sweet thanks @stalniy!
